spring:
    application:
        name: potato-chat
    datasource:
        url: jdbc:mariadb://localhost:3306/potato_chat?useSSL=false&serverTimezone=UTC
        username: root
        password: Jhan562!
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
jwt:
    expiration_time: 86400000
    secret: 444aee4a0e959c4d0deb4a965e44cae39dcb2a73a89b32a402f86e9b009ff4a0d44e59685154afe4609ea98d85595cc248d109d7ae9087179d8bec1aacd9e1ad
